#(1) Name : Zhiwei Deng
#(2) USC ID Number : 3669230452
#(3) USC Email : zhiweide@usc.edu
#(4) Submission Date : 01/28/2020

all:
	g++ -o Problem2-a-U.exe Problem2-a-U.cpp image.cpp
	g++ -o Problem2-a-G.exe Problem2-a-G.cpp image.cpp
	g++ -o Problem2-b.exe Problem2-b.cpp image.cpp
	g++ -o Problem2-c.exe Problem2-c.cpp image.cpp