all:
	#Compile Source Files
	g++ -o Problem2a Problem2a.cpp image.cpp
	g++ -o Problem2b Problem2b.cpp image.cpp
	g++ -o Problem2c Problem2c.cpp image.cpp
	g++ -o Problem2d Problem2d.cpp image.cpp

run:
	#Run Programs
	./Problem2a
	./Problem2b
	./Problem2c
	./Problem2d

clear:
	-rm -f Problem2a
	-rm -f Problem2b
	-rm -f Problem2c
	-rm -f Problem2d