#(1) Name : Zhiwei Deng
#(2) USC ID Number : 3669230452
#(3) USC Email : zhiweide@usc.edu
#(4) Submission Date : 01/28/2020

all:
	g++ -o Problem1-a.exe Problem1-a.cpp image.cpp
	g++ -o Problem1-b.exe Problem1-b.cpp image.cpp
	g++ -o Problem1-cA.exe Problem1-cA.cpp image.cpp
	g++ -o Problem1-cB.exe Problem1-cB.cpp image.cpp