#(1) Name : Zhiwei Deng
#(2) USC ID Number : 3669230452
#(3) USC Email : zhiweide@usc.edu
#(4) Submission Date : 02/16/2020

all:
	#Part A Source Files
	g++ -o Problem1-a Problem1-a.cpp image.cpp

run:
	#Part A Run
	#The First one is Threshold for Gallery
	#The Second one is Threshold for Dogs
	./Problem1-a 0.07 0.10 

clear:
	-rm -f Problem1-a
	-rm -f Images/Gallery_Gray.raw
	-rm -f Images/Gallery_GrayX.raw
	-rm -f Images/Gallery_GrayY.raw
	-rm -f Images/Gallery_SB_Map.raw
	-rm -f Images/Gallery_Edges.raw
	-rm -f Images/Dogs_Gray.raw
	-rm -f Images/Dogs_GrayX.raw
	-rm -f Images/Dogs_GrayY.raw
	-rm -f Images/Dogs_SB_Map.raw
	-rm -f Images/Dogs_Edges.raw